### ISSUE TITLE
SID - DataCalls module: enhancements

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/icesSD#18]
Thanks for the preview Mike, some of these are questions and some comments/enhancements if agreed:

1. The field 'Data Aggregation Level' refers only to temporal aggregation (month, year etc.). So should the title be 'Temporal aggregation level' (this would avoid ambiguity)
2. Are all fields optional? would be good to have some indication by colour or symbol if that's not the case
3. Surveys field, is this free text, how do multiple surveys get inputted, shouldn't this run from a vocab and perhaps this doesn't lend itself to a flat table?
4. I foresee viewing issues with having so many columns and scrolling across, you quickly lose track of which row relates to which country
5. Will there be a guidance doc accompanying the release of this, especially for new stock coordinators?
6. I'm just guessing, but wouldn't it be depending on the stock category that there is a general idea of what fields would be required i.e. for categories 1-3 you would be asking for a certain number of these fields. If so, couldn't 'off the shelf' profiles be defined and then the Stock coordinator could pick these as a starting point to cut down all the manual box ticking
7. In the same tack as above, a 'copy down' button would be really useful to apply the same settings to an additional country
8. What does it mean to 'publish' a data call here. I assume it doesn't mean to publish it, but prepare it for some human eye check? Can you clarify what happens when you press the button?

**Comment by mikeydrew** [comment]
HI Neil, responses to the above
1. I will leave this for Rui to decide as he defined the columns
2. Only country and data aggregation level are required. Validation is in place to enforce this.
3. At the moment, there is no vocab defined. This has been discussed for the next phase using  Maybe using Anna O's comprehensive list. Maybe, we should just hide this column for now. Rui, please clarify.
4. I agree, there are a lot of columns, maybe some alternate row colouring will help.
5. Documentation or preferably a video.
6. Not sure about this, Rui, please clarify
7. This was something I had in mind for the next phase as a lot of the time the sames values are in each country record
8. Publish in this context means that the SC has checked the data and has made the relevant changes.

**Comment by neil-ices-dk** [comment]
Thanks Mike,
2) can you make it clearer they are required?
3) be careful here, it will be a mess to untangle the more this information is populated with no control. 
5) Document is need to have, video a nice to have
8) Still not clear - where does it publish it to precisely - who sees this?

**Comment by mikeydrew** [comment]
Hi Neil, please see answers below.
2) Sure can, I will add some styling
3) I know, this is how it has been done so far with the old annex 1 spreadsheets. A vocab is the optimal choice, if everyone can agree on one ;)
5) Agreed
8) It doesn't publish it anywhere per se, what Rui wanted was a mechanism in place whereby advice can see whether a Data Call has been checked by a SC and a confirmation that the info is correct. Think of it as a "time stamp field" and a "confirmed by field" in the database. These are used for internal checking and will be used to contact SCs who have not made the "declaration".

**Comment by neil-ices-dk** [comment]
- comments to updated version:
9. Excel Icon is tiny and hard to spot, bigger icon and some buffering to move it out from the edge might help

**Comment by Rui-Catarino** [comment]
Hi Neil,

I'll go through the remaining of unanswered questions:

 1- We have tried to minimise the size of the column headers to make it more readable. Given that the field is a drop down and there are only temporal options I would think as it is should be suffice. However, I don’t have strong feelings and if you think it makes it clearer I’m happy to be changed. 
 
3- The idea was to force stock assessors to fill in the surveys. We are not using the information just yet but it will be a good to collect it and cross check it with the RCG's list and also with what we already have. It will make it easier (famous last words) to check inconsistences with 3 sources of data rather than just two. Hopefully after this we will be able to make some more progress with the surveys.

6- You are right that different categories have different data needs and we could possibly hide certain columns based on stock category. However, there are exceptions (as always) were stocks with a higher category (usually cat 3) are so due to uncertainty around data or strong retrospective patterns rather than lack of data(usually low sampling or known bias). Not sure how to tackle this one…

8- Regarding the publish button, see your point of view. Mike's proposed solution seems a good option are you happy with it? 
 
Also in general the coordinators that have been testing the system have all finished checking and approving their stocks in less than half an hour. Next year 95% of the stock assessors should just make minor adjustments and most will only click the approve button unless there is a benchmark.

**Comment by neil-ices-dk** [comment]
6) one way to handle this in the interface (for your phase 2) could be to group the headings i.e. core, landings, discards etc. and then use an HTML 5 control to expand collapse horizontally (like Doodle polls do).
